name: Github Pages Deploy

on:
  push:
    branches:
      - "dev-deploy"

jobs:
  build:
  runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [16.13.2]

  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install and build
      run: mpm install && npm run build

    - name: Deploy
      uses: SabrinaPVaz/react-portfolio-website
      with:
        branch: dev-deploy
        folder: build
      